<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Label="BlazorCommon">
    <CompressionEnabled>false</CompressionEnabled>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <PropertyGroup Label="ElectronNetCommon">
    <ElectronVersion>41.3.0</ElectronVersion>
    <ElectronBuilderVersion>26.8.1</ElectronBuilderVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlazorBlueprint.Components" Version="3.9.6" />
    <PackageReference Include="ElectronNET.Core" Version="0.5.0-pre.73" />
    <PackageReference Include="ElectronNET.Core.AspNet" Version="0.5.0-pre.73" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Electron\custom_main.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>.electron\custom_main.js</TargetPath>
    </None>
  </ItemGroup>

</Project>
